input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => {
      "observability_mode" => "local-elasticsearch"
      "aws_cloudwatch_log_group_hint" => "/ecs/credit-recovery-local/%{[service]}"
      "aws_cloudwatch_log_stream_hint" => "docker-compose/%{[service]}"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "credit-recovery-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => json_lines
  }
}
